server:
  port : 8085
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/learn?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
logging:
  file:
    name: log-demo-test.log
    path: /demo-logs-test
  level:
    org:
      hibernate : error 
    dz:
      acs:
        learn: WARN
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 1Mb
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
