spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
logging:
  file:
    name: mem.log
  level:
    root : info  	
    dz:
      acs:
        app: debug
  logback:
    rollingpolicy:
      max-file-size: 1Mb
server:
  port: 8080  
  